server:
  port: 8080
  servlet:
    context-path: /personal-expense-tracker

spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:postgresql://localhost:5433/personal_expense_tracker_db}
    driverClassName: org.postgresql.Driver
    username: ${DBMS_USERNAME:postgres}
    password: ${DBMS_PASSWORD:02587169}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.jdbc.time_zone: UTC

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 3600
  refreshable-duration: 36000
